version: '3.8'

services:
  dnn-benchmarks:
    build:
      context: .
    volumes:
      - ./container_reports:/reports
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
